[package]
name = "rust_wasm_websys_utils"
version = "0.4.5"
authors = ["bestia.dev"]
homepage = "https://bestia.dev"
edition = "2018"
description = "micro crate web_sys and js_sys functions for my project"
repository = "https://github.com/bestia-dev/rust_wasm_websys_utils"
readme = "README.md"
license = "MIT"
keywords = ["wasm","web_sys","js_sys"]
categories = ["wasm","web-programming"]
# publish as a crates.io library. Only this files.
publish = true
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/*",
]

[dependencies]
unwrap = "1.2.1"
wasm-bindgen = { version = "0.2.60", features = ["serde-serialize"] }
#newer version of rand do not have smallring
rand = { version = "0.7.3", features = ["wasm-bindgen","small_rng"] }
js-sys = "0.3"
serde ="1.0.106"
serde_json = "1.0"
# newer futures have unstable .await
wasm-bindgen-futures = "0.4.10"

[dependencies.web-sys]
version = "0.3.33"
features = [
  "console",
  "Document",
  "Element",
  "ErrorEvent",
  "Event",
  "EventListener",
  "EventTarget",
  "History",
  "HtmlAudioElement",
  "HtmlElement",
  "HtmlImageElement",
  "HtmlInputElement",
  "HtmlMediaElement",
  "KeyboardEvent",
  "Location",
  "MouseEvent",
  "Navigator",
  "Node",
  "Request",
  "RequestCache",
  "RequestCredentials",
  "RequestInit",
  "RequestMode",
  "RequestRedirect",
  "Response",
  "Storage",
  "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.8"